# Exceptions
validation.subscribe.self.error=User cannot subscribe to himself
validation.subscription.not.exist=Subscription does not exist
validation.subscription.already.exists=Subscription already exists
exception.user.not_found=User with id: {0} not found
